prepare_data.py:
  datasets:
    ground_truth_sectors_shapefile: data/aoi.shp
    ground_truth_swimming_pools_shapefile: data/labels_fussgaengerstreifen.shp
    other_sectors_shapefile: data/prediction_labels.shp
    other_swimming_pools_shapefile: data/prediction_labels.shp
  zoom_level: 17
  output_folder: output_CH

generate_tilesets.py:
  debug_mode: False
  datasets:
    aoi_tiles_geojson: output_CH/aoi_z16_tiles.geojson
    ground_truth_labels_geojson: output_CH/ground_truth_labels.geojson
    other_labels_geojson: output_CH/other_labels.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://wms.geo.admin.ch/service
      layers: ch.swisstopo.swissimage
      srs: "EPSG:2056"
  output_folder: output_CH
  tile_size: 512 # per side, in pixels
  overwrite: False
  n_jobs: 20
  COCO_metadata:
    year: 2020
    version: 1.0
    description: 2018-20 Swissimage
    contributor: swisstopo
    url: 
    license:
      name: Unknown
      url:
    category:
        name: "fussgaengerstreifen"
        supercategory: "infrastructure"
        
train_model.py:
    working_folder: output_CH
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_training_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: '../detectron2_config_ch.yaml' # path relative to the working_folder
    model_weights:
        model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
        
make_predictions.py:
    working_folder: output_CH
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_prediction_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
        oth: COCO_oth.json
    detectron2_config_file: '../detectron2_config_ch.yaml' # path relative to the working_folder
    model_weights:
        pth_file: './logs/model_final.pth'
  
assess_predictions.py:
  datasets:
    ground_truth_labels_geojson: output_CH/ground_truth_labels.geojson
    other_labels_geojson: output_CH/other_labels.geojson
    image_metadata_json: output_CH/img_metadata.json
    split_aoi_tiles_geojson: output_CH/split_aoi_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: output_CH/trn_predictions_at_0dot05_threshold.pkl
      val: output_CH/val_predictions_at_0dot05_threshold.pkl
      tst: output_CH/tst_predictions_at_0dot05_threshold.pkl
      oth: output_CH/oth_predictions_at_0dot05_threshold.pkl
  output_folder: output_CH/assessment